#!/bin/bash
# $Id: newroll,v 1.18 2021/05/17 13:45:07 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/newroll,v $
# $Revision: 1.18 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: newroll,v 1.18 2021/05/17 13:45:07 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-p] [-v]|-V"
prep=1
verbose=1
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;
		-p) prep=0;shift;;	
		-v) verbose=0;shift;;
		-V) echo "$cmd $Revision: 1.18 $ $Date: 2021/05/17 13:45:07 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done

cmd=`basename $0`

mntPt=/media/cf
[ $verbose -eq 0 ] &&  echo "$cmd: Mount point is $mntPt."
srcDir=$mntPt/DCIM/101EOS5D
[ $verbose -eq 0 ] &&  echo "$cmd: Source directory $srcDir."
destBase=~/cwf/pics/roll
[ $verbose -eq 0 ] &&  echo "$cmd: Roll directory $destBase."

# Mount the sdhc/cf card
mount | 
if grep -q "$mntPt" ;then
	sudo umount $mntPt
	[ $verbose -eq 0 ] &&  echo "$cmd: $mntPt unmounted."
fi
for dev in sdj1 sdk1 ;do
  if [ -e /dev/$dev ];then
	if ! mount /dev/$dev ;then 
		echo "$cmd: on $mntPt failed." >&2; continue
	else
		[ $verbose -eq 0 ] &&{
			echo "$cmd: Device $dev mounted."
		}	
	fi
	if [ -d $mntPt/DCIM/101EOS5D ] ;then 
		break
	else
		[ $verbose -eq 0 ] &&{
				echo "$cmd: Device $dev is not a CF card." >&2;
			}
		umount $mntPt
		continue
	fi	
  else
	[ $verbose -eq 0 ] && echo "$cmd: Device /dev/$dev does not exist." >&2
  fi 
done
if [ ! -d $mntPt/DCIM/101EOS5D ] ;then 
	echo "$cmd: No images found in.">&2
	exit
fi
##

cd $srcDir ||{ echo "$cmd: cd to $srcDir failed." >&2;exit 1 ;}
noImages=`ls *.CR2 2>/dev/null |wc -l`
[ $noImages -lt 1 ] &&{ echo "$cmd: No images found in $srcDir.">&2
	cd ~
	umount $mntPt
	exit 1 
}

lastFile=`ls | awk 'END{print}'`
[ $verbose -eq 0 ] &&  echo "$cmd: Last file  $lastFile."
lastDate=`stat -c %y $lastFile |awk '{print gensub("-","","g",$1)}'`
[ $verbose -eq 0 ] && echo "$cmd: last date $lastDate."
cd "$destBase"
roll=`ls -d ????????-???? | awk -F"-" 'END{print $2 + 1}'`
destDir="$destBase/$lastDate-$roll"
[ $verbose -eq 0 ] && echo "$cmd: New roll is $destDir."
mkdir -p $destDir/raw || { echo "$cmd: mkdir $destDir failed." >&2;exit 1 ;}
cd $srcDir
mv *.CR2 $destDir/raw/
[ $verbose -eq 0 ] && {  n=`(cd $destDir/raw;ls|wc -l)`
			 echo "$cmd: $n CR2 files moved to $destDir/raw."
}


if ls *.MOV >/dev/null 2>&1 ;then
	mkdir -p $destDir/mov 
	[ $verbose -eq 0 ] && echo "$cmd: moving .MOV files to $destDir/mov." 
	mv *.MOV $destDir/mov/
fi
cd ~
umount $mntPt 
cd $destDir/raw
if [ $prep -eq 0 ] ;then
	[ $verbose -eq 0 ] && flags='-v'
	preppics $flags *.CR2
fi



