#!/bin/bash
# $Id: newroll,v 1.4 2020/10/26 14:41:43 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/newroll,v $
# $Revision: 1.4 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: newroll,v 1.4 2020/10/26 14:41:43 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-h) hostid=$2;shift 2;;			
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.4 $ $Date: 2020/10/26 14:41:43 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done

cmd=`basename $0`
verbose=1
case $1 in
	-v) verbose=0;shift;;
esac

mntPt=/media/sdk1
[ $verbose -eq 0 ] &&  echo $mntPt
srcDir=$mntPt/DCIM/101EOS5D
[ $verbose -eq 0 ] &&  echo $srcDir 
destBase=~/cwf/pics/roll
[ $verbose -eq 0 ] &&  echo $destBase 

# Mount the sdhc/cf card
mount | 
if grep -q "$mntPt" ;then
	sudo umount $mntPt
	[ $verbose -eq 0 ] &&  echo "$mntPt unmounted"
fi
[ -e /dev/sdk1 ]||{ echo "$cmd: device /dev/sdk1 does not exist." >&2;exit 1 ;} 
mount /dev/sdk1 ||{ echo "$cmd: on $mntPt failed" >&2;exit 1 ;}
##

cd $srcDir ||{ echo "$cmd: cd to $srcDir failed" >&2;exit 1 ;}
noImages=`ls *.CR2 2>/dev/null |wc -l`
[ $noImages -lt 1 ] &&{ echo "$cmd: no images found in $srcDir">&2
	umount $mntPt
	exit 1 
}

lastFile=`ls | awk 'END{print}'`
[ $verbose -eq 0 ] &&  echo "$lastFile"
lastDate=`stat -c %y $lastFile |awk '{print gensub("-","","g",$1)}'`
[ $verbose -eq 0 ] && echo $lastDate
cd "$destBase"
roll=`ls -d ????????-???? | awk -F"-" 'END{print $2 + 1}'`
destDir="$destBase/$lastDate-$roll"
[ $verbose -eq 0 ] && echo $destDir
mkdir -p $destDir/raw || { echo "$cmd: mkdir $destDir failed" >&2;exit 1 ;}
cd $srcDir
[ $verbose -eq 0 ] && echo "$cmd: CR2 file moved to $destDir/raw" 
mv *.CR2 $destDir/raw/
if test -e *.MOV ;then
	mkdir -p $destDir/mov 
	[ $verbose -eq 0 ] && echo "$cmd: moving .MOV files to $destDir/mov" 
	mv *.MOV $destDir/mov/
fi
cd /
umount $mntPt 



